// Jochona controller glyph system (M1). Generated by
// scripts/generate-glyph-fonts.py from assets/vendor/kenney-input-prompts-1.5.zip
// (CC0, Kenney Input Prompts 1.5). DO NOT EDIT BY HAND - edit the generator.
//
// Glyphs ship as per-family icon FONTS, so a glyph is just a Text: it inherits
// the theme color and scales with the type ramp. Logical names are unified on
// Xbox vocabulary; PlayStation/Switch/Steam sources land on the same buttons.
//
//   Text {
//       text: Glyphs.glyph(Glyphs.family, "a")
//       font.family: Glyphs.fontFamily(Glyphs.family)
//       color: Tokens.textPrimary
//   }
//
// family: "xbox" | "playstation" | "nintendo" | "steam" | "generic"
// Unknown families resolve to "generic"; "auto" follows the detected pad (M2).
pragma Singleton
import QtQuick 2.0

QtObject {
    id: root

    // Default prompt family until the M2 controller manager reports identity;
    // writable so the UI can bind it to the connected controller's family.
    property string family: "xbox"

    readonly property var fontFiles: {
              "xbox": "kenney_input_xbox_series",
              "playstation": "kenney_input_playstation_series",
              "nintendo": "kenney_input_nintendo_switch",
              "steam": "kenney_input_steam_deck",
              "generic": "kenney_input_generic"
          }

    property var _loaders: ({})

    Component.onCompleted: {
        var loaders = ({})
        var names = Object.keys(fontFiles)
        for (var i = 0; i < names.length; i++) {
            loaders[names[i]] = fontLoaderComp.createObject(root, {
                "source": "qrc:/fonts/" + fontFiles[names[i]] + ".ttf"
            })
        }
        root._loaders = loaders
    }

    // QtObject has no default property — the Component must hang off an
    // explicit property or instantiation of the singleton fails at runtime.
    readonly property Component fontLoaderComp: Component {
        FontLoader {}
    }

    function fontFamily(family) {
        var key = (family in glyphs) ? family : "generic"
        var loader = root._loaders[key]
        return loader && loader.name.length > 0 ? loader.name : "Inter"
    }

    // Returns the glyph character, or "" for unknown names/families.
    function glyph(family, logical) {
        var key = (family in glyphs) ? family : "generic"
        var ch = glyphs[key][logical]
        if (ch === undefined) {
            ch = glyphs["generic"][logical]
        }
        return ch === undefined ? "" : ch
    }

    // logical name -> character, per family (generated; unified vocabulary)
    readonly property var glyphs: {
        "xbox": {
            "a": "\u{E004}",
            "b": "\u{E006}",
            "x": "\u{E01E}",
            "y": "\u{E020}",
            "lb": "\u{E043}",
            "rb": "\u{E049}",
            "lt": "\u{E047}",
            "rt": "\u{E04D}",
            "dpad_up": "\u{E035}",
            "dpad_down": "\u{E024}",
            "dpad_left": "\u{E028}",
            "dpad_right": "\u{E02B}",
            "stick_left": "\u{E053}",
            "stick_right": "\u{E05B}",
            "menu": "\u{E014}",
            "back": "\u{E01C}",
            "guide": "\u{E041}",
            "share": "\u{E016}"
        },
        "playstation": {
            "a": "\u{E04B}",
            "b": "\u{E041}",
            "x": "\u{E051}",
            "y": "\u{E053}",
            "lb": "\u{E078}",
            "rb": "\u{E080}",
            "lt": "\u{E07C}",
            "rt": "\u{E084}",
            "dpad_up": "\u{E060}",
            "dpad_down": "\u{E057}",
            "dpad_left": "\u{E05B}",
            "dpad_right": "\u{E05E}",
            "stick_left": "\u{E04D}",
            "stick_right": "\u{E04F}",
            "menu": "\u{E024}",
            "back": "\u{E01E}",
            "guide": "\u{E03F}",
            "share": "\u{E00B}",
            "touchpad": "\u{E030}"
        },
        "nintendo": {
            "a": "\u{E004}",
            "b": "\u{E006}",
            "x": "\u{E018}",
            "y": "\u{E01A}",
            "lb": "\u{E00A}",
            "rb": "\u{E010}",
            "lt": "\u{E01C}",
            "rt": "\u{E01E}",
            "dpad_up": "\u{E02B}",
            "dpad_down": "\u{E022}",
            "dpad_left": "\u{E026}",
            "dpad_right": "\u{E029}",
            "stick_left": "\u{E05E}",
            "stick_right": "\u{E066}",
            "menu": "\u{E00E}",
            "back": "\u{E00C}",
            "guide": "\u{E008}",
            "share": "\u{E016}"
        },
        "steam": {
            "a": "\u{E001}",
            "b": "\u{E003}",
            "x": "\u{E01D}",
            "y": "\u{E01F}",
            "lb": "\u{E007}",
            "rb": "\u{E013}",
            "lt": "\u{E009}",
            "rt": "\u{E015}",
            "dpad_up": "\u{E02C}",
            "dpad_down": "\u{E023}",
            "dpad_left": "\u{E027}",
            "dpad_right": "\u{E02A}",
            "stick_left": "\u{E034}",
            "stick_right": "\u{E03C}",
            "menu": "\u{E00F}",
            "back": "\u{E01B}",
            "guide": "\u{E005}",
            "share": "\u{E011}",
            "touchpad": "\u{E04B}"
        },
        "generic": {

        }
    }
}
