#!/usr/bin/env python3
"""Generate the controller glyph system from the vendored Kenney Input Prompts pack.

Inputs (tracked):  assets/vendor/kenney-input-prompts-1.5.zip  (CC0)
Outputs (tracked): app/fonts/kenney_input_*.ttf                (per-family glyph fonts)
                   app/gui/style/Glyphs.qml                    (logical-name singleton)

Glyph FONTS (not sprites) are the delivery format: a glyph Text inherits the
active theme color and scales with the type ramp for free. Logical names are
unified across families on Xbox vocabulary; PlayStation's
cross/circle/square/triangle and Switch's A/B/X/Y land on the same logical
buttons. Face-button swap preferences remain a UI concern, not a font one.
"""
import re
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ZIP = ROOT / "assets" / "vendor" / "kenney-input-prompts-1.5.zip"
FONTS_DIR = ROOT / "app" / "fonts"
OUT_QML = ROOT / "app" / "gui" / "style" / "Glyphs.qml"

# vendored pack folder -> (family key, font basename)
FAMILIES = {
    "Xbox Series": ("xbox", "kenney_input_xbox_series"),
    "PlayStation Series": ("playstation", "kenney_input_playstation_series"),
    "Nintendo Switch": ("nintendo", "kenney_input_nintendo_switch"),
    "Steam Deck": ("steam", "kenney_input_steam_deck"),
    "Generic": ("generic", "kenney_input_generic"),
}

LOGICAL = {
    "a":        {"xbox": "xbox_button_a", "playstation": "playstation_button_cross",
                 "nintendo": "switch_button_a", "steam": "steamdeck_button_a"},
    "b":        {"xbox": "xbox_button_b", "playstation": "playstation_button_circle",
                 "nintendo": "switch_button_b", "steam": "steamdeck_button_b"},
    "x":        {"xbox": "xbox_button_x", "playstation": "playstation_button_square",
                 "nintendo": "switch_button_x", "steam": "steamdeck_button_x"},
    "y":        {"xbox": "xbox_button_y", "playstation": "playstation_button_triangle",
                 "nintendo": "switch_button_y", "steam": "steamdeck_button_y"},
    "lb":       {"xbox": "xbox_lb", "playstation": "playstation_trigger_l1",
                 "nintendo": "switch_button_l", "steam": "steamdeck_button_l1"},
    "rb":       {"xbox": "xbox_rb", "playstation": "playstation_trigger_r1",
                 "nintendo": "switch_button_r", "steam": "steamdeck_button_r1"},
    "lt":       {"xbox": "xbox_lt", "playstation": "playstation_trigger_l2",
                 "nintendo": "switch_button_zl", "steam": "steamdeck_button_l2"},
    "rt":       {"xbox": "xbox_rt", "playstation": "playstation_trigger_r2",
                 "nintendo": "switch_button_zr", "steam": "steamdeck_button_r2"},
    "dpad_up":     {"xbox": "xbox_dpad_up", "playstation": "playstation_dpad_up",
                    "nintendo": "switch_buttons_up", "steam": "steamdeck_dpad_up"},
    "dpad_down":   {"xbox": "xbox_dpad_down", "playstation": "playstation_dpad_down",
                    "nintendo": "switch_buttons_down", "steam": "steamdeck_dpad_down"},
    "dpad_left":   {"xbox": "xbox_dpad_left", "playstation": "playstation_dpad_left",
                    "nintendo": "switch_buttons_left", "steam": "steamdeck_dpad_left"},
    "dpad_right":  {"xbox": "xbox_dpad_right", "playstation": "playstation_dpad_right",
                    "nintendo": "switch_buttons_right", "steam": "steamdeck_dpad_right"},
    "stick_left":  {"xbox": "xbox_stick_l_press", "playstation": "playstation_button_l3",
                    "nintendo": "switch_stick_l_press", "steam": "steamdeck_stick_l_press"},
    "stick_right": {"xbox": "xbox_stick_r_press", "playstation": "playstation_button_r3",
                    "nintendo": "switch_stick_r_press", "steam": "steamdeck_stick_r_press"},
    "menu":     {"xbox": "xbox_button_menu", "playstation": "playstation5_button_options",
                 "nintendo": "switch_button_plus", "steam": "steamdeck_button_options"},
    "back":     {"xbox": "xbox_button_view", "playstation": "playstation5_button_create",
                 "nintendo": "switch_button_minus", "steam": "steamdeck_button_view"},
    "guide":    {"xbox": "xbox_guide", "playstation": "playstation_button_analog",
                 "nintendo": "switch_button_home", "steam": "steamdeck_button_guide"},
    "share":    {"xbox": "xbox_button_share", "playstation": "playstation4_button_share",
                 "nintendo": "switch_button_sync", "steam": "steamdeck_button_quickaccess"},
    "touchpad": {"playstation": "playstation5_touchpad", "steam": "steamdeck_trackpad_l"},
}

HEX_RE = re.compile(r"^([a-z0-9_]+):\s*U\+([0-9A-Fa-f]{4,6})\s*$")

QML_HEAD = """// Jochona controller glyph system (M1). Generated by
// scripts/generate-glyph-fonts.py from assets/vendor/kenney-input-prompts-1.5.zip
// (CC0, Kenney Input Prompts 1.5). DO NOT EDIT BY HAND - edit the generator.
//
// Glyphs ship as per-family icon FONTS, so a glyph is just a Text: it inherits
// the theme color and scales with the type ramp. Logical names are unified on
// Xbox vocabulary; PlayStation/Switch/Steam sources land on the same buttons.
//
//   Text {
//       text: Glyphs.glyph(Glyphs.family, "a")
//       font.family: Glyphs.fontFamily(Glyphs.family)
//       color: Tokens.textPrimary
//   }
//
// family: "xbox" | "playstation" | "nintendo" | "steam" | "generic"
// Unknown families resolve to "generic"; "auto" follows the detected pad (M2).
pragma Singleton
import QtQuick 2.0

QtObject {
    id: root

    // Default prompt family until the M2 controller manager reports identity;
    // writable so the UI can bind it to the connected controller's family.
    property string family: "xbox"

    readonly property var fontFiles: {FONTS}

    property var _loaders: ({})

    Component.onCompleted: {
        var loaders = ({})
        var names = Object.keys(fontFiles)
        for (var i = 0; i < names.length; i++) {
            loaders[names[i]] = fontLoaderComp.createObject(root, {
                "source": "qrc:/fonts/" + fontFiles[names[i]] + ".ttf"
            })
        }
        root._loaders = loaders
    }

    // QtObject has no default property — the Component must hang off an
    // explicit property or instantiation of the singleton fails at runtime.
    readonly property Component fontLoaderComp: Component {
        FontLoader {}
    }

    function fontFamily(family) {
        var key = (family in glyphs) ? family : "generic"
        var loader = root._loaders[key]
        return loader && loader.name.length > 0 ? loader.name : "Inter"
    }

    // Returns the glyph character, or "" for unknown names/families.
    function glyph(family, logical) {
        var key = (family in glyphs) ? family : "generic"
        var ch = glyphs[key][logical]
        if (ch === undefined) {
            ch = glyphs["generic"][logical]
        }
        return ch === undefined ? "" : ch
    }

    // logical name -> character, per family (generated; unified vocabulary)
    readonly property var glyphs: {
{GLYPHS}
    }
}
"""


def load_map(zf: zipfile.ZipFile, folder: str) -> dict:
    base = FAMILIES[folder][1]
    name = f"{folder}/Fonts/{base}_map.txt"
    out = {}
    for line in zf.read(name).decode("utf-8").splitlines():
        m = HEX_RE.match(line.strip())
        if m:
            out[m.group(1)] = int(m.group(2), 16)
    return out


def main() -> None:
    zf = zipfile.ZipFile(ZIP)
    FONTS_DIR.mkdir(exist_ok=True)

    fonts = {}
    maps = {}
    for folder, (key, base) in FAMILIES.items():
        data = zf.read(f"{folder}/Fonts/{base}.ttf")
        (FONTS_DIR / f"{base}.ttf").write_bytes(data)
        print(f"wrote app/fonts/{base}.ttf ({len(data)} bytes)")
        fonts[key] = base
        maps[key] = load_map(zf, folder)

    generic = maps["generic"]
    blocks = []
    missing = []
    for key in ["xbox", "playstation", "nintendo", "steam", "generic"]:
        fam = maps[key]
        entries = []
        for logical, per_family in LOGICAL.items():
            src = per_family.get(key)
            cp = fam.get(src) if src else None
            if cp is None and src:
                missing.append(f"{key}.{logical} (source '{src}' not in family map)")
                cp = generic.get(src)  # generic names often shared across families
            if cp is None:
                continue
            entries.append(f'            "{logical}": "\\u{{{cp:X}}}"')
        blocks.append(f'        "{key}": {{\n' + ",\n".join(entries) + "\n        }")

    fonts_block = ",\n              ".join(f'"{k}": "{v}"' for k, v in fonts.items())
    qml = QML_HEAD.replace("{FONTS}", "{\n              " + fonts_block + "\n          }")
    qml = qml.replace("{GLYPHS}", ",\n".join(blocks))
    OUT_QML.write_text(qml, encoding="utf-8")
    print(f"wrote app/gui/style/Glyphs.qml "
          f"({len(LOGICAL)} logical glyphs x {len(FAMILIES)} families)")
    for m in missing:
        print(f"note: {m}")


if __name__ == "__main__":
    main()
